'use client'
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {getSession, SessionProvider, useSession} from "next-auth/react";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import React from "react";


const inter = Inter({subsets: ["latin"]});

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
   // const {data: session} = useSession();
    return (
        <html lang="en">
        <body className={inter.className}>
        <SessionProvider>
            {children}
            <ToastContainer position={"top-right"}
                            autoClose={2000}
                            hideProgressBar={false}
                            newestOnTop={false}
                            closeOnClick
                            rtl={false}
                            pauseOnFocusLoss
            />
        </SessionProvider>
        </body>
        </html>
    );
}